### ISSUE TITLE
FileNotFoundError: File b'../Data/salami-data-public-master/beats/1000.beats.txt' does not exist

### ISSUE THREAD

**Issue by Irinnisar** [mleimeister/SegmentationCNN#1]
I get the error when run the feature extraction code, Whats wrong with the input data? Are those in the Data folder not complete?

**Comment by mleimeister** [comment]
Hi Irinnisar, 

the data folder as it is just contains splits of training and test data. The data needs to be downloaded first and the paths adapted to your local setting. In order to get the audio files and annotations, please see here: http://ddmal.music.mcgill.ca/research/salami/annotations, https://github.com/DDMAL/SALAMI/blob/master/SALAMI_download.py

The beat tracking has then to be run using the MADMOM toolbox: https://github.com/CPJKU/madmom
This will generate the `.beats.txt` files that caused the error.

Altogether, however, the code was still in a work-in-progress phase and never got consolidated. If you're interested in using the CNN code, I'd recommend rewriting the feature extraction and evaluation part in Python, as I originally intended but then got discontinued.

Cheers, Matthias

**Comment by bwinsto2** [comment]
Getting the same error. Not sure if it is looking for audio files that aren't in the SALAMI download :(
